### ISSUE TITLE
Responsive Images

### ISSUE THREAD

**Issue by nklansford** [nklansford/keyway#12]
I would like to show and hide my call to action image for different media queries. I currently have one file called "responsive" with this:
```
@import "vars";
@media only screen and (max-width: 320px) {
  .cta{
    .cta__image--1{
      display: block;
    }
    .cta__image--2{
      display: none;
    }
    .cta__image--3{
      display: none;
    }
  }
}
@media only screen and (max-width: 768px){
  .cta{
    .cta__image--1{
      display: none;
    }
    .cta__image--2{
      display: block;
    }
    .cta__image--3{
      display: none;
    }
  }
}
@media only screen and (max-width: 1200px){
.cta{
  .cta__image--1{
    display: none;
  }
  .cta__image--2{
    display: none;
  }
  .cta__image--3{
    display: block;
  }
}
}
```
(note the vars issue in the previous comment.) And I can see that it is going over to my .css file correctly. However, when I test it in the browser it only breaks at the tablet size and shows the desktop image for mobile and tablet and all 3 for desktop. Any ideas?

**Comment by philschanely** [comment]
Your queries are not quite logical. Because you're using max-width what you're saying is that the contained styles should apply _up to_ that width. So in the first one, image 1 is only visible up to 320px and hidden thereafter. You probably want that visible up to 768 instead. Then the second one is visible up to 768 but you probably want it visible up to 1200. Finally, the last one is visible up to 1200 and you probably want it visible above 1200... You have several options. Here are two I recommend:

### 1. Adjust media queries to `min-width` and implement mobile first. 

This means that the mobile styles become default and are not guarded by a media query. Then the subsequent style override using `min-width` filters for the desired breakpoints. They'd look like this:

```scss
// Default styles are unguarded so they apply until overridden by others
.cta__image--1{
  display: block;
}
.cta__image--2{
  display: none;
}
.cta__image--3{
  display: none;
}

// Styles for tablet and higher; these apply beginning at 768px
@media (min-width: 768px) {
  .cta__image--1{
    display: none;
  }
  .cta__image--2{
    display: block;
  }
  .cta__image--3{
    display: none;
  }
}

// Styles for desktop and higher; this apply beginning at 1200px
@media (min-width: 1200px) {
  .cta__image--1 {
    display: none;
  }
  .cta__image--2 {
    display: none;
  }
  .cta__image--3 {
    display: block;
  }
}
```

### 2. Revise approach to use true responsive images.

We now have the ability in modern browsers to stack on images in a single `img` tag using the `srcset` and `sizes` attributes like this:

```html
<img class="cta__image"
  src="/images/keyway-cta-mobile.png"
  srcset="/images/keyway-cta-mobile.png 238w,
    /images/keyway-cta-tablet.png 327w,
    /images/keyway-cta-desktop.png 460w"
  sizes="(min-width: 1200px) 460px,
    (min-width: 768px) 327px,
    238px"
/>
```

In general:
1. We provide a default image still with `src`.
2. We provide a set of images with `srcset` where we provide the path then the pixel width using `238w` for `238px`.
3. We provide a media query stack with `sizes` that is similar to the set discussed above using `min-width` but just in the reverse order. The query is followed by the image size that should be matched at that media query.

Here's a resource for learning more: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
