### ISSUE TITLE
centering sub-content not working

### ISSUE THREAD

**Issue by nklansford** [nklansford/keyway#13]
I have 
```
.cta{
  border: solid 3px red;
  width: $width-mobile;
  margin: $layout-center;
}
```
which compiles to 
```
.cta {
  border: solid 3px red;
  width: 320px;
  margin: 0px auto; }
```
(red is there for temporary visualization) however, my items in .cta are not centering. I have tried all I know `justify-content: center;` `align-items: center;` etc. However the only one that seems to work is `text-align: center` but this aligns my text to be centered (which is logical) but not what I want. Anything obvious I am missing?

**Comment by philschanely** [comment]
First up, ensure your overall document is set up with responsive widths beginning outward and moving in. So in this situation, the restricted width on body isn't helping. Do this first:

```scss
body{
  margin: $layout-center;
  width: $width-mobile;
  border: solid 3px blue;

  @media (min-width: 768px) {
    width: $width-tablet;
  }

  @media (min-width: 1200px) {
    width: $width-desktop;
  }
}
```

**Comment by philschanely** [comment]
Here is a sample of making the cta component responsive.

**/src/index.html**

```html
...
<section class="cta">
  <div class="cta__image">
    <img src="/images/keyway-cta-mobile.png"
      srcset="/images/keyway-cta-mobile.png 238w,
              /images/keyway-cta-tablet.png 327w,
              /images/keyway-cta-desktop.png 460w"
      sizes="(min-width: 1200px) 460px,
             (min-width: 768px) 327px,
             238px"
    />
  </div> 
  <p class="cta__holler">We Know, Nowbody Adventures Like You.</p>
  <p class="cta__btn btn">Build Your Interest Page</p>
  <p class="cta__body">Let’s face it: planning a trip is no easy feat. Here at Keyway, we take away the stress so that you can freely explore what you want to do. Hotel? Treehouse? We’ve seen it all and want to help you find the most exciting or relaxing get-away. Just set up your interest page, enter your price range, pick some dates and we’ll tell you what is possible.</p>
</section>
...
```

**/src/scss/modules/_cta.scss**

```css
.cta {
  margin: 72px 12px 101px;
  display: grid;
  grid-template-columns: 100%;
  grid-row-gap: 18px;
  grid-template-areas:
    "image"
    "holler"
    "btn"
    "body";

  @media (min-width: 768px) {
    margin: 72px 56px;
    display: grid;
    grid-template-columns: 327px 290px;
    grid-column-gap: 39px;
    grid-row-gap: 47px;
    grid-template-areas:
      "image holler"
      "image btn"
      "body  body";
  }

  @media (min-width: 1200px) {
    margin-top: 55px 78px 147px;
    grid-template-columns: 507px 460px;
    grid-column-gap: 77px;
    grid-row-gap: 65px;
    grid-template-areas:
      "image holler"
      "image body"
      "image btn";
  }
}

.cta__body {
  grid-area: body;
  margin-top: 40px;

  @include type-setup(1.6rem, 2.3rem);

  @media (min-width: 768px) {
    margin-top: 0;
  }
}

.cta__btn {
  grid-area: btn;
  align-self: start;
  margin: 0;
  width: 100%;
  max-width: 290px;
}

.cta__image {
  grid-area: image;
  margin-bottom: 20px;

  @media (min-width: 768px) {
    margin-bottom: 0;
  }

  img {
    width: 100%;
    display: block;
  }
}

.cta__holler {
  grid-area: holler;
  align-self: end;
  margin: 0px;
  text-align: center;

  @include type-setup(3.1rem, 4.1rem);

  @media (min-width: 1200px) {
    text-align: left;

    @include type-setup(3.5rem, 4.3rem);
  }
}
```
